/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ActivityId = bigint;
export type ActivityType = { 'fertilizing' : null } |
  { 'harvest' : null } |
  { 'irrigation' : null } |
  { 'pestControl' : null } |
  { 'planting' : null };
export interface Cell { 'value' : Value, 'name' : string }
export interface DashboardSummary {
  'totalFarms' : bigint,
  'totalAreaHectares' : number,
  'mostRecentActivity' : [] | [FieldActivity],
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface FarmPlot {
  'id' : PlotId,
  'latitude' : number,
  'areaHectares' : number,
  'name' : string,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'longitude' : number,
  'locationLabel' : string,
  'cropType' : string,
}
export interface FarmPlotInput {
  'latitude' : number,
  'areaHectares' : number,
  'name' : string,
  'longitude' : number,
  'locationLabel' : string,
  'cropType' : string,
}
export interface FarmPlotUpdate {
  'latitude' : number,
  'areaHectares' : number,
  'name' : string,
  'longitude' : number,
  'locationLabel' : string,
  'cropType' : string,
}
export interface FarmerProfile {
  'displayName' : string,
  'defaultRegion' : string,
}
export interface FieldActivity {
  'id' : ActivityId,
  'activityType' : ActivityType,
  'plotId' : PlotId,
  'date' : Timestamp,
  'createdAt' : Timestamp,
  'notes' : string,
}
export interface FieldActivityInput {
  'activityType' : ActivityType,
  'plotId' : PlotId,
  'date' : Timestamp,
  'notes' : string,
}
export type PlotId = bigint;
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  /**
   * / Log an activity against one of the caller's plots.
   */
  'addActivity' : ActorMethod<[FieldActivityInput], FieldActivity>,
  /**
   * / Create a farm plot owned by the caller.
   */
  'addPlot' : ActorMethod<[FarmPlotInput], FarmPlot>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Delete one of the caller's plots and its activities.
   */
  'deletePlot' : ActorMethod<[PlotId], boolean>,
  'execute' : ActorMethod<[string], Result>,
  /**
   * / Return the backend's public API documentation as Markdown.
   */
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Summarize the caller's farms, total area, and most recent activity.
   */
  'getDashboardSummary' : ActorMethod<[], DashboardSummary>,
  /**
   * / Return one of the caller's plots, or null when it does not exist or is not theirs.
   */
  'getPlot' : ActorMethod<[PlotId], [] | [FarmPlot]>,
  /**
   * / Return the caller's profile, or null when none has been saved yet.
   */
  'getProfile' : ActorMethod<[], [] | [FarmerProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / List the caller's activities for a plot, newest first, optionally filtered by type.
   */
  'listActivities' : ActorMethod<
    [PlotId, [] | [ActivityType]],
    Array<FieldActivity>
  >,
  /**
   * / List all farm plots owned by the caller.
   */
  'listPlots' : ActorMethod<[], Array<FarmPlot>>,
  'schema' : ActorMethod<[], string>,
  /**
   * / Create or replace the caller's profile.
   */
  'setProfile' : ActorMethod<[string, string], FarmerProfile>,
  /**
   * / Update one of the caller's plots.
   */
  'updatePlot' : ActorMethod<[PlotId, FarmPlotUpdate], FarmPlot>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];