/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const ActivityType = IDL.Variant({
  'fertilizing' : IDL.Null,
  'harvest' : IDL.Null,
  'irrigation' : IDL.Null,
  'pestControl' : IDL.Null,
  'planting' : IDL.Null,
});
export const PlotId = IDL.Nat;
export const Timestamp = IDL.Int;
export const FieldActivityInput = IDL.Record({
  'activityType' : ActivityType,
  'plotId' : PlotId,
  'date' : Timestamp,
  'notes' : IDL.Text,
});
export const ActivityId = IDL.Nat;
export const FieldActivity = IDL.Record({
  'id' : ActivityId,
  'activityType' : ActivityType,
  'plotId' : PlotId,
  'date' : Timestamp,
  'createdAt' : Timestamp,
  'notes' : IDL.Text,
});
export const FarmPlotInput = IDL.Record({
  'latitude' : IDL.Float64,
  'areaHectares' : IDL.Float64,
  'name' : IDL.Text,
  'longitude' : IDL.Float64,
  'locationLabel' : IDL.Text,
  'cropType' : IDL.Text,
});
export const FarmPlot = IDL.Record({
  'id' : PlotId,
  'latitude' : IDL.Float64,
  'areaHectares' : IDL.Float64,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'longitude' : IDL.Float64,
  'locationLabel' : IDL.Text,
  'cropType' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const DashboardSummary = IDL.Record({
  'totalFarms' : IDL.Nat,
  'totalAreaHectares' : IDL.Float64,
  'mostRecentActivity' : IDL.Opt(FieldActivity),
});
export const FarmerProfile = IDL.Record({
  'displayName' : IDL.Text,
  'defaultRegion' : IDL.Text,
});
export const FarmPlotUpdate = IDL.Record({
  'latitude' : IDL.Float64,
  'areaHectares' : IDL.Float64,
  'name' : IDL.Text,
  'longitude' : IDL.Float64,
  'locationLabel' : IDL.Text,
  'cropType' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addActivity' : IDL.Func([FieldActivityInput], [FieldActivity], []),
  'addPlot' : IDL.Func([FarmPlotInput], [FarmPlot], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deletePlot' : IDL.Func([PlotId], [IDL.Bool], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardSummary' : IDL.Func([], [DashboardSummary], ['query']),
  'getPlot' : IDL.Func([PlotId], [IDL.Opt(FarmPlot)], ['query']),
  'getProfile' : IDL.Func([], [IDL.Opt(FarmerProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listActivities' : IDL.Func(
      [PlotId, IDL.Opt(ActivityType)],
      [IDL.Vec(FieldActivity)],
      ['query'],
    ),
  'listPlots' : IDL.Func([], [IDL.Vec(FarmPlot)], ['query']),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'setProfile' : IDL.Func([IDL.Text, IDL.Text], [FarmerProfile], []),
  'updatePlot' : IDL.Func([PlotId, FarmPlotUpdate], [FarmPlot], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const ActivityType = IDL.Variant({
    'fertilizing' : IDL.Null,
    'harvest' : IDL.Null,
    'irrigation' : IDL.Null,
    'pestControl' : IDL.Null,
    'planting' : IDL.Null,
  });
  const PlotId = IDL.Nat;
  const Timestamp = IDL.Int;
  const FieldActivityInput = IDL.Record({
    'activityType' : ActivityType,
    'plotId' : PlotId,
    'date' : Timestamp,
    'notes' : IDL.Text,
  });
  const ActivityId = IDL.Nat;
  const FieldActivity = IDL.Record({
    'id' : ActivityId,
    'activityType' : ActivityType,
    'plotId' : PlotId,
    'date' : Timestamp,
    'createdAt' : Timestamp,
    'notes' : IDL.Text,
  });
  const FarmPlotInput = IDL.Record({
    'latitude' : IDL.Float64,
    'areaHectares' : IDL.Float64,
    'name' : IDL.Text,
    'longitude' : IDL.Float64,
    'locationLabel' : IDL.Text,
    'cropType' : IDL.Text,
  });
  const FarmPlot = IDL.Record({
    'id' : PlotId,
    'latitude' : IDL.Float64,
    'areaHectares' : IDL.Float64,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'longitude' : IDL.Float64,
    'locationLabel' : IDL.Text,
    'cropType' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const DashboardSummary = IDL.Record({
    'totalFarms' : IDL.Nat,
    'totalAreaHectares' : IDL.Float64,
    'mostRecentActivity' : IDL.Opt(FieldActivity),
  });
  const FarmerProfile = IDL.Record({
    'displayName' : IDL.Text,
    'defaultRegion' : IDL.Text,
  });
  const FarmPlotUpdate = IDL.Record({
    'latitude' : IDL.Float64,
    'areaHectares' : IDL.Float64,
    'name' : IDL.Text,
    'longitude' : IDL.Float64,
    'locationLabel' : IDL.Text,
    'cropType' : IDL.Text,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addActivity' : IDL.Func([FieldActivityInput], [FieldActivity], []),
    'addPlot' : IDL.Func([FarmPlotInput], [FarmPlot], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deletePlot' : IDL.Func([PlotId], [IDL.Bool], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardSummary' : IDL.Func([], [DashboardSummary], ['query']),
    'getPlot' : IDL.Func([PlotId], [IDL.Opt(FarmPlot)], ['query']),
    'getProfile' : IDL.Func([], [IDL.Opt(FarmerProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listActivities' : IDL.Func(
        [PlotId, IDL.Opt(ActivityType)],
        [IDL.Vec(FieldActivity)],
        ['query'],
      ),
    'listPlots' : IDL.Func([], [IDL.Vec(FarmPlot)], ['query']),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'setProfile' : IDL.Func([IDL.Text, IDL.Text], [FarmerProfile], []),
    'updatePlot' : IDL.Func([PlotId, FarmPlotUpdate], [FarmPlot], []),
  });
};

export const init = ({ IDL }) => { return []; };